services:
  plantcare-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: 181960
      POSTGRES_DB: plantcare
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - plantcare-network

#  backend:
#    build: ./
#    depends_on:
#      - plantcare-postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/plantcare?useSSL=false
#      SPRING_DATASOURCE_USERNAME: student
#      SPRING_DATASOURCE_PASSWORD: 181960
#    ports:
#      - "8086:8080"
#    networks:
#      - plantcare-network

#  frontend:
#    build: ./frontend
#    depends_on:
#      - backend
#    ports:
#      - "80:80"
#    networks:
#      - plantcare-network

networks:
  plantcare-network:
    driver: bridge

volumes:
  postgres-data: